Add working EUPS packaging of treecorr
lsst/treecorr pull request #1
Opened 2017-07-27 20:59 UTC by wmwv

2017-07-27 22:11 UTC, timj requested changes
I don't believe you need the .cfg file for a python package. The .cfg file allows scons to work out what include paths and libraries to use when linking.

Also, do you need the build() override in the .cfg.sh file? It seems to build for me without it.

2017-07-28 02:30 UTC, wmwv commented
Thank you.  `treecorr.cfg` removed.  `build() {...}` removed from `eupspkg.cfg.sh`.

2017-07-28 02:32 UTC, wmwv commented
Forced-pushed an updated branch that rebase squashed over these unneeded bits.

2017-07-28 15:10 UTC, timj approved these changes

2017-07-28 15:31 UTC, merged